
/* Generated by scripts/gen.js */
  
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
  
import { AvatarSkillDepotExcelConfigData } from "./types/AvatarSkillDepotExcelConfigData";
import { ReliquaryExcelConfigData } from "./types/ReliquaryExcelConfigData";
import { WeaponExcelConfigData } from "./types/WeaponExcelConfigData";
import { ReliquaryMainPropExcelConfigData } from "./types/ReliquaryMainPropExcelConfigData";
import { ReliquaryAffixExcelConfigData } from "./types/ReliquaryAffixExcelConfigData";
  
class GameData {
  public static AvatarSkillDepotExcelConfigData = this.readFile<AvatarSkillDepotExcelConfigData>(resolve(__dirname, "../data/gamedata/AvatarSkillDepotExcelConfigData.json"));
  public static ReliquaryExcelConfigData = this.readFile<ReliquaryExcelConfigData>(resolve(__dirname, "../data/gamedata/ReliquaryExcelConfigData.json"));
  public static WeaponExcelConfigData = this.readFile<WeaponExcelConfigData>(resolve(__dirname, "../data/gamedata/WeaponExcelConfigData.json"));
  public static ReliquaryMainPropExcelConfigData = this.readFile<ReliquaryMainPropExcelConfigData>(resolve(__dirname, "../data/gamedata/ReliquaryMainPropExcelConfigData.json"));
  public static ReliquaryAffixExcelConfigData = this.readFile<ReliquaryAffixExcelConfigData>(resolve(__dirname, "../data/gamedata/ReliquaryAffixExcelConfigData.json"));
  private static readFile<T>(filePath: string) {
    try {
      const file = readFileSync(filePath);
      if (file === undefined) {
        throw new Error(`File ${filePath} is undefined`);
      }
      return JSON.parse(file.toString()) as T;
    } catch (error) {
      throw error;
    }
  }
}
  
export default GameData;
  