
/* Generated by scripts/gen.js */
  
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
  
import { Characters } from "./types/Characters";
import { Affixes } from "./types/Affixes";
import { Costumes } from "./types/Costumes";
import { Loc } from "./types/Loc";
import { Namecards } from "./types/Namecards";
  
class EnkaAPIStore {
  public static characters = this.readFile<Characters>(resolve(__dirname, "../data/store/characters.json"));
  public static affixes = this.readFile<Affixes>(resolve(__dirname, "../data/store/affixes.json"));
  public static costumes = this.readFile<Costumes>(resolve(__dirname, "../data/store/costumes.json"));
  public static loc = this.readFile<Loc>(resolve(__dirname, "../data/store/loc.json"));
  public static namecards = this.readFile<Namecards>(resolve(__dirname, "../data/store/namecards.json"));
  private static readFile<T>(filePath: string) {
    try {
      const file = readFileSync(filePath);
      if (file === undefined) {
        throw new Error(`File ${filePath} is undefined`);
      }
      return JSON.parse(file.toString()) as T;
      } catch (error) {
        throw error;
      }
    }
  }
  
  export default EnkaAPIStore;
  